/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":                "#f9f9fe",
        "surface":                   "#f9f9fe",
        "surface-bright":            "#f9f9fe",
        "surface-dim":               "#dad9de",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f4f3f8",
        "surface-container":         "#eeedf2",
        "surface-container-high":    "#e8e8ed",
        "surface-container-highest": "#e2e2e7",
        "surface-variant":           "#e2e2e7",
        "on-surface":                "#1a1c1f",
        "on-surface-variant":        "#43474f",
        "primary":                   "#001e40",
        "on-primary":                "#ffffff",
        "primary-container":         "#003366",
        "on-primary-container":      "#799dd6",
        "primary-fixed":             "#d5e3ff",
        "primary-fixed-dim":         "#a7c8ff",
        "on-primary-fixed":          "#001b3c",
        "on-primary-fixed-variant":  "#1f477b",
        "inverse-primary":           "#a7c8ff",
        "secondary":                 "#545f72",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#d5e0f7",
        "on-secondary-container":    "#586377",
        "secondary-fixed":           "#d8e3fa",
        "secondary-fixed-dim":       "#bcc7dd",
        "on-secondary-fixed":        "#111c2c",
        "on-secondary-fixed-variant":"#3c475a",
        "tertiary":                  "#381300",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#592300",
        "on-tertiary-container":     "#d8885c",
        "tertiary-fixed":            "#ffdbca",
        "tertiary-fixed-dim":        "#ffb690",
        "on-tertiary-fixed":         "#341100",
        "on-tertiary-fixed-variant": "#723610",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
        "outline":                   "#737780",
        "outline-variant":           "#c3c6d1",
        "inverse-surface":           "#2f3034",
        "inverse-on-surface":        "#f1f0f5",
        "surface-tint":              "#3a5f94",
        "on-background":             "#1a1c1f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      fontFamily: {
        sans: ["Fira Sans", "sans-serif"],
      },
      fontSize: {
        "data-label":   ["11px", { lineHeight: "14px",  fontWeight: "500" }],
        "label-caps":   ["12px", { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "600" }],
        "body-base":    ["14px", { lineHeight: "20px",  fontWeight: "400" }],
        "headline-lg":  ["24px", { lineHeight: "32px",  fontWeight: "600" }],
        "metric-display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":  ["18px", { lineHeight: "24px",  fontWeight: "600" }],
      },
      spacing: {
        "gutter":             "16px",
        "base":               "4px",
        "card-gap":           "20px",
        "container-padding":  "24px",
        "section-margin":     "40px",
      },
      boxShadow: {
        card: "0 4px 6px -1px rgba(0,51,102,0.04)",
      },
    },
  },
  plugins: [],
}
